spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/spring
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formate_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true

application:
  security:
    jwt:
      secret-key: FF96814BEF37EDB1A23F6A5761F6DFF96814BEF37EDB1A23F6A5761F6D
      expiration: 86400000 # 1 Day
      refresh-token:
        expiration: 604800000 # 7 Days