spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/spring
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formate_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true